### ISSUE TITLE
which kind of generator did you create?

### ISSUE THREAD

**Issue by diomed** [AhmerAli412/GridLayoutGenetrator#1]
Is it html one or react one? Because you didn't specify anywhere it's a react one. But it is, since **className** doesnt work in HTML

maybe provide both options?

```
<div className="grid grid-rows-2 grid-cols-2 gap-2">
<div className='row-start-1 row-end-2 col-start-1 col-end-2 h-30 w-30 bg-blue-300'></div>
<div className='row-start-2 row-end-3 col-start-2 col-end-3 h-30 w-30 bg-blue-300'></div>
<div className='row-start-2 row-end-3 col-start-1 col-end-2 h-30 w-30 bg-blue-300'></div>
</div>
```

**Comment by AhmerAli412** [comment]
yes its a react one will do for both (html and react js)  tomorrow.. stay tuned

**Comment by AhmerAli412** [comment]
> Is it html one or react one? Because you didn't specify anywhere it's a react one. But it is, since **className** doesnt work in HTML
> 
> maybe provide both options?
> 
> ```
> <div className="grid grid-rows-2 grid-cols-2 gap-2">
> <div className='row-start-1 row-end-2 col-start-1 col-end-2 h-30 w-30 bg-blue-300'></div>
> <div className='row-start-2 row-end-3 col-start-2 col-end-3 h-30 w-30 bg-blue-300'></div>
> <div className='row-start-2 row-end-3 col-start-1 col-end-2 h-30 w-30 bg-blue-300'></div>
> </div>
> ```

**Comment by AhmerAli412** [comment]
Hey, i added the html code feature too...now you can get both jsx and html code for selected grids!

**Comment by diomed** [comment]
> Hey, i added the html code feature too...now you can get both jsx and html code for selected grids!

thanks! I appreciate it!

**Comment by diomed** [comment]
btw you could add your generator to list of Awesome Tailwind stuff

https://github.com/aniftyco/awesome-tailwindcss

**Comment by AhmerAli412** [comment]
ohh how to do this i didn't understand can u pls elaborate more how to do this?

**Comment by diomed** [comment]
it's simple. just check how people previously commited their pages and then you do same:
here are guidelines:
https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md

**Comment by AhmerAli412** [comment]
thanks and if you have more suggestions to improve my tool do tell..i will update!

**Comment by diomed** [comment]
> thanks and if you have more suggestions to improve my tool do tell..i will update!

someone mentioned subgrids

**Comment by diomed** [comment]
also - gap does nothing visually.

and it obviously should. when changing gap number - there should be visual difference.

**Comment by AhmerAli412** [comment]
> also - gap does nothing visually.
> 
> and it obviously should. when changing gap number - there should be visual difference.

ok i will update it

**Comment by AhmerAli412** [comment]
> also - gap does nothing visually.
> 
> and it obviously should. when changing gap number - there should be visual difference.

i done the gap thing now u can see visually!
